### ISSUE TITLE
Empty filename when creating an archive

### ISSUE THREAD

**Issue by glpzzz** [lxqt/lxqt-archiver#129]
##### Expected Behavior
Filename input to be filled with an appropiate filename for the case. 

##### Current Behavior
Empty filename box. Also, its need to type the file extension. Selecting from dropdown is not working.

![image](https://user-images.githubusercontent.com/13596248/67421642-eeb52e80-f59e-11e9-9b29-3b801442f7ab.png)

##### Possible Solution
If a file or directory is selected, its name. If a group of file inside a directory selected, the name of the parent directory holding them.

##### Steps to Reproduce (for bugs)
1. Right click a file on pcmanfm-qt, select compress

##### Context
The idea is not having to select the directory to create the archive nor type its name.

##### System Information
lxqt-0.1.0 latest git changes, the same for pcmanfm-qt and libfm-qt

**Comment by tsujan** [comment]
Right.

I've done it in [Arqiver](https://github.com/tsujan/Arqiver) but not in lxqt-archiver yet. It was in my TODO list but things are a little more complex with lxqt-archiver.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lxqt-archiver/pull/130

The archive name is made out of the name of the first file/folder in the command-line (which may be the first or last selected file, depending on the selection method) — using the name of the parent folder would be confusing because that folder may contain other files.

The user could always change the name if he wants to.

**Comment by glpzzz** [comment]
The right directory is chosen but filename is still empty.

**Comment by tsujan** [comment]
> filename is still empty.

It isn't when you use the Compress item in the context menu of pcmanfm-qt -- the right directory was also chosen before the change.
