### ISSUE TITLE
cannot open RPM

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-archiver#192]
Followup to #158

##### Expected Behavior
Package content is visible (readonly).

##### Current Behavior
Generic dialog appears: "Command cannot be executed."

##### Steps to Reproduce (for bugs)
Open any RPM archive.

##### System Information
* Distribution & Version: Manjaro 20.1 
* Kernel: 5.4
* Qt Version: 5.15.1 
* libqtxdg Version: 3.5.0-3
* lxqt-build-tools Version: not relevant
* Package version: 0.2.0

**Comment by jubalh** [comment]
I can confirm this.

I tested to open https://build.opensuse.org/package/binary/download/network/profanity/openSUSE_Tumbleweed/x86_64/profanity-0.9.5-55.6.x86_64.rpm which looks like this:
![showlxqt](https://user-images.githubusercontent.com/1658215/97562461-f2fdfe00-19e1-11eb-9bb8-63abad9c8f79.png)

Distribution: openSUSE Tumbleweed
But running lxqt-archiver 0.2.0. Will later try with latest git.

**Comment by tsujan** [comment]
@jubalh, yes, I know. The same archive is opened correctly by `bsdtar` (and Arqiver). See https://github.com/lxqt/lxqt-archiver/issues/156#issuecomment-620765019

The problem is in the core library we've inherited from file-roller. We may need to see whether new versions of file-roller have fixed it and import the fix if that's the case.

**Comment by jubalh** [comment]
> The problem is in the core library we've inherited from file-roller.

I remember looking at the code in the past and already there wondered: is there no library? Taking code from a certain point in time from another project just by copying makes it hard to keep getting updates for it.

**Comment by tsujan** [comment]
> Taking code from a certain point in time from another project just by copying makes it hard to keep getting updates for it.

Although I didn't write lxqt-archiver, I think it was a very good idea not to reinvent the wheel. In the same way, Engrampa was forked from file-roller, or Nemo from Nautilus.

We can make the core library better — as we've done so far — but, sometimes, it's wiser to copy fixes if there are any fixes at all. A reason is that no LXQt developer has been able to give his full free time to lxqt-archiver (for example, I work on it whenever I find time for it).

**Comment by tsujan** [comment]
I took a look at file-roller's code. It used `libarchive` (bsdtar) instead of `rpm2cpio`, although the latter wasn't removed from the source :) 

Instead of importing file-roller's code, which needed a lot of time that I didn't have, I used `bsdtar` inside `fr-command-rpm.c` and lxqt-archiver opened `profanity-0.9.5-55.6.x86_64.rpm` correctly:

![rpm](https://user-images.githubusercontent.com/981076/97598439-383f2180-1a1c-11eb-9cb6-f0d77b7ea9f4.png)

The implementation is incomplete because I didn't consider extraction but there is hope.

**Comment by antis81** [comment]
@tsujan I took a look at file-roller's code. It used libarchive (bsdtar) instead of rpm2cpio,…

Now that's interesting, because e.g. Ark also utilizes libarchive (and provides a plugin strategy for unsuppported compression codecs). OTOH it makes the question mark in my head even bigger. Just why all the CLI based stuff? :question: :slightly_smiling_face:

**Comment by tsujan** [comment]
> Just why all the CLI based stuff?

Because there's no other way. For example, `zip` has no header. Moreover, one wants to use 7z, gzip, bsdtar,... when they exist and show error messages when they don't, without build dependencies.

**Comment by tsujan** [comment]
OK, the extraction was also a pice of cake; just needed the correct options. So, `bsdtar` will save us from the RPM headache; we could get rid of `rpm2cpio` in lxqt-archiver :)

I should also work on error messages because "Failed to execute the command" is anything but informative. It'll take some time...

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lxqt-archiver/pull/193. @jubalh, I requested your review.

**Comment by jubalh** [comment]
I like this solution much better!
