### ISSUE TITLE
`Failed to execute the command.` when creating ZIP or 7Z

### ISSUE THREAD

**Issue by absolutelynothinghere** [lxqt/lxqt-archiver#349]
##### Expected Behavior

`lxqt-archiver -a archive.zip ./*` should create a ZIP archive and quit. Same thing for `.7z`
I already have `7z` and `zip` installed, and can create archives normally using them.

##### Current Behavior

An error message is displayed: `Failed to execute the command.`

##### Possible Solution

No idea.

##### Steps to Reproduce (for bugs)

1. Run `lxqt-archiver -a archive.zip ./*` or `lxqt-archiver -a archive.7z ./*`

##### Context

I'm just trying to create an archive...

##### System Information

* Distribution & Version: Void Linux (rolling)
* Kernel: 5.15.85
* Qt Version: 5.15.7
* libqtxdg Version: N/A
* lxqt-build-tools Version: ???
* Package version: 0.7.0

**Comment by tsujan** [comment]
Not reproducible.

Probably, you haven't installed the needed libraries for creating `ziip` and `7zip`.

**Comment by absolutelynothinghere** [comment]
>Probably, you haven't installed the needed libraries for creating zip and 7z.

Which are...? Closing this without elaboration doesn't help.

I have these binaries installed: `zip unzip 7z`  
As well as these libraries: `libzip minizip gzip`  
So please tell me what exactly I'm missing.

Engrampa works fine with these, so what is the problem with LXQT? And how can I properly diagnose the problem? There are no clues at all on the command line which is very bizarre.

**Comment by tsujan** [comment]
> Closing this without elaboration doesn't help.

This place is the bug tracker. There was no bug; hence closing.

> So please tell me what exactly I'm missing.

You miss nothing. I said, "*Probably*,..", because I didn't have time to consult the jungle of codes — which I did now.

> How can I properly diagnose the problem?

`Failed to execute the command` means `zip`/`7z` is found but can't be executed. The app can't tell why; I neither. *Maybe* there's something wrong with the build in your distro. To make sure, you could compile `lxqt-archver` from the source without installing it:

```
mkdir build && cd build
cmake ..
make
```

Then, you could use the binary `build/src/lxqt-archiver` to see if it works properly.
